name: flutter_test_utils
description: A Flutter library that can help simplify writing tests
version: 1.0.2
homepage: https://github.com/cyenite/flutter_test_utils.git

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter


